name: Generate summary cards

on:
  schedule:
    - cron: "0 3 * * *"   # roda todo dia 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: micdog22
          BRANCH: main
          CONFIG: |
            {
              "languages": {"hide": ["Jupyter Notebook"]},
              "commits": {"count_private": true, "include_all_commits": true},
              "output": "profile-summary-card-output",
              "templates": ["transparent"]
            }
      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update summary cards" || echo "no changes"
          git push
